services:
  web-streamer:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: cat-monitor-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # Mapujemy tylko dane, które aplikacja generuje, 
      # a nie cały kod źródłowy (dzięki temu kod w obrazie jest bezpieczny)
      - ./server/captures:/app/captures
      - ./server/logs:/app/logs
    environment:
      - APP_ENV=development
      - PYTHONUNBUFFERED=1